### PR TITLE
Gradle support 

### LINKED ISSUE #5: Migrate from Maven to Gradle
The project is currently built using Maven, would like to move to Gradle. 

- [ ] Build project using Gradle
- [ ] Add Usage details to README.md

### PR DESCRIPTION
**Pull request by tom-bell**
Adds Gradle support to close #5

Let me know if this is missing anything. I've updated the documentation to reflect the changes.

### CODE REVIEW

**Comment by haroon-sheikh** [comment]
- [ ] Remove maven related files/docs

**Review by haroon-sheikh — CHANGES_REQUESTED** [review]
- [ ] Remove maven related files/docs
- [ ] Update .travis config to use gradle instead

**Comment by tom-bell** [comment]
What is the travis config actually doing here? uploading a maven snapshot? Not really worked with it before.

**Comment by tom-bell** [comment]
Probably not going to get round to this again, apologies. Will leave the code around if you want to take it further.

**Pull request closed without merging**
